In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [4]:
df_matches= pd.read_csv("../data/raw/historical/WorldCupMatches.csv")
df_matches.head()
df_cups = pd.read_csv("../data/raw/historical/WorldCups.csv")
df_players = pd.read_csv("../data/raw/historical/WorldCupPlayers.csv")
df_cups.head()
df_players.head(10)

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event
0,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Alex THEPOT,GK,NaN
1,201,1096,MEX,LUQUE Juan (MEX),S,0,Oscar BONFIGLIO,GK,NaN
2,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Marcel LANGILLER,NaN,G40'
3,201,1096,MEX,LUQUE Juan (MEX),S,0,Juan CARRENO,NaN,G70'
4,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Ernest LIBERATI,NaN,NaN
5,201,1096,MEX,LUQUE Juan (MEX),S,0,Rafael GARZA,C,NaN
6,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Andre MASCHINOT,NaN,G43' G87'
7,201,1096,MEX,LUQUE Juan (MEX),S,0,Hilario LOPEZ,NaN,NaN
8,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Etienne MATTLER,NaN,NaN
9,201,1096,MEX,LUQUE Juan (MEX),S,0,Dionisio MEJIA,NaN,NaN

In [5]:
print(df_matches.shape)
df_matches.info()

(4572, 20)
<class 'pandas.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  852 non-null    float64
 1   Datetime              852 non-null    str
 2   Stage                 852 non-null    str
 3   Stadium               852 non-null    str
 4   City                  852 non-null    str
 5   Home Team Name        852 non-null    str
 6   Home Team Goals       852 non-null    float64
 7   Away Team Goals       852 non-null    float64
 8   Away Team Name        852 non-null    str
 9   Win conditions        852 non-null    str
 10  Attendance            850 non-null    float64
 11  Half-time Home Goals  852 non-null    float64
 12  Half-time Away Goals  852 non-null    float64
 13  Referee               852 non-null    str
 14  Assistant 1           852 non-null    str
 15  Assistant 2           852 non-null    str
 16  RoundID               852 non-null    float64
 17  MatchID               852 non-null    float64
 18  Home Team Initials    852 non-null    str
 19  Away Team Initials    852 non-null    str
dtypes: float64(8), str(12)
memory usage: 714.5 KB

In [6]:
#we are finding how much data are missing
df_matches.isnull().sum()

Year                    3720
Datetime                3720
Stage                   3720
Stadium                 3720
City                    3720
Home Team Name          3720
Home Team Goals         3720
Away Team Goals         3720
Away Team Name          3720
Win conditions          3720
Attendance              3722
Half-time Home Goals    3720
Half-time Away Goals    3720
Referee                 3720
Assistant 1             3720
Assistant 2             3720
RoundID                 3720
MatchID                 3720
Home Team Initials      3720
Away Team Initials      3720
dtype: int64

In [7]:
#understanding the numbers in our data
df_matches.describe()

,Year,Home Team Goals,Away Team Goals,Attendance,Half-time Home Goals,Half-time Away Goals,RoundID,MatchID
count,852.000000,852.000000,852.000000,850.000000,852.000000,852.000000,8.520000e+02,8.520000e+02
mean,1985.089202,1.811033,1.022300,45164.800000,0.708920,0.428404,1.066177e+07,6.134687e+07
std,22.448825,1.610255,1.087573,23485.249247,0.937414,0.691252,2.729613e+07,1.110572e+08
min,1930.000000,0.000000,0.000000,2000.000000,0.000000,0.000000,2.010000e+02,2.500000e+01
25%,1970.000000,1.000000,0.000000,30000.000000,0.000000,0.000000,2.620000e+02,1.188750e+03
50%,1990.000000,2.000000,1.000000,41579.500000,0.000000,0.000000,3.370000e+02,2.191000e+03
75%,2002.000000,3.000000,2.000000,61374.500000,1.000000,1.000000,2.497220e+05,4.395006e+07
max,2014.000000,10.000000,7.000000,173850.000000,6.000000,5.000000,9.741060e+07,3.001865e+08

In [8]:
print(df_cups.shape)
print(df_cups.columns)

(20, 10)
Index(['Year', 'Country', 'Winner', 'Runners-Up', 'Third', 'Fourth',
       'GoalsScored', 'QualifiedTeams', 'MatchesPlayed', 'Attendance'],
      dtype='str')

In [9]:
#from above result we found that there is a runners-up column ,which can be problem due to -
#changing it 
df_cups = df_cups.rename(columns={'Runners-Up': 'RunnersUp'})
print(df_cups.columns)
df_cups.dtypes

Index(['Year', 'Country', 'Winner', 'RunnersUp', 'Third', 'Fourth',
       'GoalsScored', 'QualifiedTeams', 'MatchesPlayed', 'Attendance'],
      dtype='str')

Year              int64
Country             str
Winner              str
RunnersUp           str
Third               str
Fourth              str
GoalsScored       int64
QualifiedTeams    int64
MatchesPlayed     int64
Attendance          str
dtype: object

In [10]:
df_cups['Attendance'].dtype
df_cups.Attendance.isnull().sum()
df_cups['Attendance'].head(10)

0      590.549
1      363.000
2      375.700
3    1.045.246
4      768.607
5      819.810
6      893.172
7    1.563.135
8    1.603.975
9    1.865.753
Name: Attendance, dtype: str

In [11]:
# since the attendance data are in invalid way 1.865.753 its an error
# so removing the dots
df_cups['Attendance'] = df_cups['Attendance'].str.replace('.',' ',regex=False)

# attendance is in str so changing it to number
df_cups['Attendance'] = pd.to_numeric(df_cups['Attendance'], errors='coerce')
df_cups['Attendance'].head(10)

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
Name: Attendance, dtype: float64

In [12]:
print(df_cups['Attendance'].dtype)
df_cups.isnull().sum()
df_cups['Attendance'].head(10)

float64

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
Name: Attendance, dtype: float64

In [13]:
df_cups = pd.read_csv('../data/raw/historical/WorldCups.csv', encoding='unicode_escape')
df_cups['Attendance'].head(10)
df_cups['Attendance'] = df_cups['Attendance'].str.strip()
df_cups['Attendance'] = df_cups['Attendance'].str.replace('.', '', regex=False) #removed the .
df_cups['Attendance'].head(10)
df_cups['Attendance'] = pd.to_numeric(df_cups['Attendance'], errors='coerce') #str to int/float
print(df_cups['Attendance'].dtype)
df_cups.isnull().sum()

int64

Year              0
Country           0
Winner            0
Runners-Up        0
Third             0
Fourth            0
GoalsScored       0
QualifiedTeams    0
MatchesPlayed     0
Attendance        0
dtype: int64

In [14]:
# created a new csv file in processed file where the clean data of worlcups.csv are kept    
df_cups.to_csv('../data/processed/cups_clean.csv', index=False)

In [15]:
print(df_matches.shape)
df_matches.isnull().sum()

(4572, 20)

Year                    3720
Datetime                3720
Stage                   3720
Stadium                 3720
City                    3720
Home Team Name          3720
Home Team Goals         3720
Away Team Goals         3720
Away Team Name          3720
Win conditions          3720
Attendance              3722
Half-time Home Goals    3720
Half-time Away Goals    3720
Referee                 3720
Assistant 1             3720
Assistant 2             3720
RoundID                 3720
MatchID                 3720
Home Team Initials      3720
Away Team Initials      3720
dtype: int64

In [16]:
# droping empty rows
df_matches = df_matches.dropna(how='all')
df_matches.shape

(852, 20)

In [17]:
df_matches.isnull().sum()

Year                    0
Datetime                0
Stage                   0
Stadium                 0
City                    0
Home Team Name          0
Home Team Goals         0
Away Team Goals         0
Away Team Name          0
Win conditions          0
Attendance              2
Half-time Home Goals    0
Half-time Away Goals    0
Referee                 0
Assistant 1             0
Assistant 2             0
RoundID                 0
MatchID                 0
Home Team Initials      0
Away Team Initials      0
dtype: int64

In [18]:
#since two missing data of attendance we remove it
df_matches = df_matches.dropna(subset='Attendance')
df_matches.isnull().sum()

Year                    0
Datetime                0
Stage                   0
Stadium                 0
City                    0
Home Team Name          0
Home Team Goals         0
Away Team Goals         0
Away Team Name          0
Win conditions          0
Attendance              0
Half-time Home Goals    0
Half-time Away Goals    0
Referee                 0
Assistant 1             0
Assistant 2             0
RoundID                 0
MatchID                 0
Home Team Initials      0
Away Team Initials      0
dtype: int64

In [19]:
df_matches.dtypes
# since year type is float which is not good so change it to int

df_matches['Year'] = df_matches['Year'].astype(int)

In [20]:
df_matches.columns.tolist()

['Year',
 'Datetime',
 'Stage',
 'Stadium',
 'City',
 'Home Team Name',
 'Home Team Goals',
 'Away Team Goals',
 'Away Team Name',
 'Win conditions',
 'Attendance',
 'Half-time Home Goals',
 'Half-time Away Goals',
 'Referee',
 'Assistant 1',
 'Assistant 2',
 'RoundID',
 'MatchID',
 'Home Team Initials',
 'Away Team Initials']

In [21]:
# since spaces can make problems we use _ instead of space
df_matches.columns = df_matches.columns.str.strip().str.lower().str.replace(' ','_').str.replace('-','_')
print(df_matches.columns.tolist())

['year', 'datetime', 'stage', 'stadium', 'city', 'home_team_name', 'home_team_goals', 'away_team_goals', 'away_team_name', 'win_conditions', 'attendance', 'half_time_home_goals', 'half_time_away_goals', 'referee', 'assistant_1', 'assistant_2', 'roundid', 'matchid', 'home_team_initials', 'away_team_initials']

In [22]:
#now we are creating a new csv file in processed file where the clean data of worldcupmatches.csv are kept
df_matches.to_csv('../data/processed/matches_clean.csv', index=False)

In [29]:
#now cleaning the players data
print(df_players.shape)
df_players.isnull().sum()

(37784, 8)

RoundID              0
MatchID              0
Team Initials        0
Coach Name           0
Line-up              0
Shirt Number         0
Player Name          0
Event            28715
dtype: int64

In [33]:
# df_players = df_players.drop(columns=['Position'])

In [32]:
df_players.columns.to_list()

['RoundID',
 'MatchID',
 'Team Initials',
 'Coach Name',
 'Line-up',
 'Shirt Number',
 'Player Name',
 'Event']

In [35]:
#we will fill the empty data of Event with 'None' so that there will be no empty/missing data
df_players['Event'] = df_players['Event'].fillna('None')
df_players.isnull().sum()

RoundID          0
MatchID          0
Team Initials    0
Coach Name       0
Line-up          0
Shirt Number     0
Player Name      0
Event            0
dtype: int64

In [37]:
df_players.columns = df_players.columns.str.strip().str.lower().str.replace(' ','_').str.replace('-','_')
df_players.isnull().sum()

roundid          0
matchid          0
team_initials    0
coach_name       0
line_up          0
shirt_number     0
player_name      0
event            0
dtype: int64

In [38]:
# data cleaned so saving the cleaned data
df_players.to_csv('../data/processed/players_clean.csv',index=False)